#define CLIENT "olobet"
#define OUT_SETUP_DIR "clients\\olobet\\"
#define OUT_SETUP_FILENAME "safetybrowser-olobet-setup"
#define APP_INSTALL_DIR "safetybrowser-olobet"
#define CLIENT_GUID "{B23AAA1B-14CD-41FE-9143-E4940F66450C}"
