#define CLIENT "twinbet"
#define OUT_SETUP_DIR "clients\\twinbet\\"
#define OUT_SETUP_FILENAME "safetybrowser-twinbet-setup"
#define APP_INSTALL_DIR "safetybrowser-twinbet"
#define CLIENT_GUID "{185C71F7-3CD1-42B8-8651-2747287ACFB7}"
